// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4TdPF_s6HevwNtuwJA4V4UzDEQydP-_E',
    appId: '1:651680108281:web:aa935fbe2df0e038ff1c28',
    messagingSenderId: '651680108281',
    projectId: 'ppb-59ad9',
    authDomain: 'ppb-59ad9.firebaseapp.com',
    storageBucket: 'ppb-59ad9.firebasestorage.app',
    measurementId: 'G-6MESX73KVZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCw4QXQu9qGh-RrpxSFacwYgIofYq3MX-c',
    appId: '1:651680108281:android:f7b84bb5aeee1008ff1c28',
    messagingSenderId: '651680108281',
    projectId: 'ppb-59ad9',
    storageBucket: 'ppb-59ad9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANpCpob17yaYJXUCX5PtCSkLY3O1ZCS8k',
    appId: '1:651680108281:ios:56e7b1b44c07237fff1c28',
    messagingSenderId: '651680108281',
    projectId: 'ppb-59ad9',
    storageBucket: 'ppb-59ad9.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANpCpob17yaYJXUCX5PtCSkLY3O1ZCS8k',
    appId: '1:651680108281:ios:56e7b1b44c07237fff1c28',
    messagingSenderId: '651680108281',
    projectId: 'ppb-59ad9',
    storageBucket: 'ppb-59ad9.firebasestorage.app',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4TdPF_s6HevwNtuwJA4V4UzDEQydP-_E',
    appId: '1:651680108281:web:3be20147ddf2f433ff1c28',
    messagingSenderId: '651680108281',
    projectId: 'ppb-59ad9',
    authDomain: 'ppb-59ad9.firebaseapp.com',
    storageBucket: 'ppb-59ad9.firebasestorage.app',
    measurementId: 'G-8L6GJQR5J1',
  );
}
